### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by ycanales** [p3lim/sublime-toxin#3]
Really nice theme/color scheme bundle!
The only thing that bothers me a bit is **there isn't a close button**, which, in my opinion is more important, doubles as a **unsaved indicator** (usually with a bright color or circle icon instead of "X" for closing), so you can have a quick glance of the opened files you're currently editing and haven't saved yet.

**Comment by p3lim** [comment]
There's a default setting called "highlight_modified_tabs", which this theme obeys, showing an indicator on the tabs that are dirty.

I will get a close tab button going in an upcoming version.

**Comment by ycanales** [comment]
Sorry I didn't know about that setting, apparently it's set to false by default or by another package I might be using. Setting it to true manually in my settings did the trick and the underline for dirty files is nice.

**Comment by p3lim** [comment]
It is set to `false` by default by Sublime Text, it's only used for themes.
I've added information about it in the README: https://github.com/p3lim/sublime-toxin/commit/770d72fe449cf34c2a890cd8ff6ca29f349229ee

**Comment by antonio-gil** [comment]
Hi!

Any update about this issue/request? I've recently "_discover_" this theme, and while it's awesome (I really like it), I also think that a "Close Button" is a must have.

Regards!

**Comment by p3lim** [comment]
@antonio-gil Since it's something that I don't personally use it's not a priority for me to add right now (and the fact that I'm really bad at any image tool doesn't help).

Feel free to add one and send me a PR to review!

**Comment by antonio-gil** [comment]
Hi @p3lim ! I have a question:

As I also don't have a "good" relationship with anything related to "graphical design", I took a look on the web and found an Icon pack from [gentleface](http://www.gentleface.com/free_icon_set.html) which had a Creative Commons license for non profit use of that pack, so, do you have any problem to use a couple of icons of the pack?

I ask because I made a couple of tests with an icon from that pack and look quite good (originally I used an couple of icons of other theme, but I didn't want to send a PR with those icons).

Regards

**Comment by p3lim** [comment]
Made some real basic pixel icons, should suffice.
